{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-api/0.25.6/dynamics-api-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-api",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-api.aar",
          "url": "dynamics-api-android-0.25.6.aar",
          "size": 13380,
          "sha512": "f161fa456bc7585d93c9012a9b289f12c1c42da5bb12b34e3bea6430560e16e67f335f25456b57db3342a615df05d8ebf5b034c407e3377a6ec624cdbda0704b",
          "sha256": "4e02e0fa033be8f5dd949ecd78ab306952e3121d639b7f2b9ecf30e812d5ae0a",
          "sha1": "7dd6dddfe8a07ac7b784dc1dc0fd57cff6c7bb84",
          "md5": "8f65d37fe515acb188c46187ca7b0b66"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-resources",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-api.aar",
          "url": "dynamics-api-android-0.25.6.aar",
          "size": 13380,
          "sha512": "f161fa456bc7585d93c9012a9b289f12c1c42da5bb12b34e3bea6430560e16e67f335f25456b57db3342a615df05d8ebf5b034c407e3377a6ec624cdbda0704b",
          "sha256": "4e02e0fa033be8f5dd949ecd78ab306952e3121d639b7f2b9ecf30e812d5ae0a",
          "sha1": "7dd6dddfe8a07ac7b784dc1dc0fd57cff6c7bb84",
          "md5": "8f65d37fe515acb188c46187ca7b0b66"
        }
      ]
    }
  ]
}
