{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource/2.12.0/resource-2.12.0.module",
    "group": "com.riseworld.launchpad.resource",
    "module": "resource",
    "version": "2.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-iosArm64Main-2.12.0.klib",
          "url": "resource-iosarm64-2.12.0.klib",
          "size": 13755,
          "sha512": "79feb13a04cc74e9c88043e91c2e9eb782669ae26d4495ce841b6cf7a796bda5ec54e04060f0e13832f9309d4c773941d5d0e8576277244bf4df61eca093f318",
          "sha256": "b895cf3b9760be1f503ca783db704f5dba13a7414e4070e0bb952b9aada880b8",
          "sha1": "f09607c3df21f2a459b5b8b68e79401c96fcc5b7",
          "md5": "119e48dad98a20a1733913abb53333e9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-iosarm64-2.12.0-metadata.jar",
          "url": "resource-iosarm64-2.12.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
