{
  "formatVersion": "1.1",
  "component": {
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-ble",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models-composite",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-ble-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.juul.tuulbox",
          "module": "collections",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-metadata-0.25.6.jar",
          "url": "dynamics-ble-0.25.6.jar",
          "size": 50033,
          "sha512": "6ba57bb704bb23483f1acbd469c31c9b638a3f8131829d212809b8610585b5750610e017ad938f6c7341ad9e76fff725f24777db9e9228151771da2ff9d128e1",
          "sha256": "4afdef32a627e173383cd6d3d830a4ea65a0826df0cc30f3307ddb84cd659b51",
          "sha1": "0aff6b772abe92659c49341b1a7d59747cac893d",
          "md5": "0990f7397fc8e883996ac1db84e0afee"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../dynamics-ble-android/0.25.6/dynamics-ble-android-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-android",
        "version": "0.25.6"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../dynamics-ble-android/0.25.6/dynamics-ble-android-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-android",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-iosarm64/0.25.6/dynamics-ble-iosarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-iosarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-iosarm64/0.25.6/dynamics-ble-iosarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-iosarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-iossimulatorarm64/0.25.6/dynamics-ble-iossimulatorarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-iossimulatorarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-iossimulatorarm64/0.25.6/dynamics-ble-iossimulatorarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-iossimulatorarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-iosx64/0.25.6/dynamics-ble-iosx64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-iosx64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-iosx64/0.25.6/dynamics-ble-iosx64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-iosx64",
        "version": "0.25.6"
      }
    }
  ]
}
