{
  "formatVersion": "1.1",
  "component": {
    "group": "com.riseworld.launchpad.kable-fork",
    "module": "models",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "models-metadata-0.8.0.jar",
          "url": "models-0.8.0.jar",
          "size": 2258,
          "sha512": "51b35dca93c68fe5bc66975e8ea4fe32946d3c0827db7f6eeff4f01d1af96a04df4b4c2b13b32dac7123a98e4272f4795b87084dbda0c1eb5407e461d2fba1ca",
          "sha256": "85f44db011d26eeaf33e89035a24e706fc6347850b94fb9da316f22f2680b648",
          "sha1": "babd1786eeeb6f83a7406ab4258b424d5868c2ca",
          "md5": "d415565a625ad866e220e70ca896ab5b"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../models-android/0.8.0/models-android-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../models-android/0.8.0/models-android-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../models-iosarm64/0.8.0/models-iosarm64-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../models-iosarm64/0.8.0/models-iosarm64-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../models-iossimulatorarm64/0.8.0/models-iossimulatorarm64-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../models-iossimulatorarm64/0.8.0/models-iossimulatorarm64-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../models-iosx64/0.8.0/models-iosx64-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../models-iosx64/0.8.0/models-iosx64-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../models-jvm/0.8.0/models-jvm-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-jvm",
        "version": "0.8.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../models-jvm/0.8.0/models-jvm-0.8.0.module",
        "group": "com.riseworld.launchpad.kable-fork",
        "module": "models-jvm",
        "version": "0.8.0"
      }
    }
  ]
}
