{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-utils/0.25.6/dynamics-utils-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-utils",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-utils-iosArm64Main-0.25.6.klib",
          "url": "dynamics-utils-iosarm64-0.25.6.klib",
          "size": 66238,
          "sha512": "8b0fb1525da52ad78b65bda1262c30cceb0b2cc003447f863ad2a914d3dae2ccb4132de6c747a9b8839ac7feab1e8076227fc692fa11e74c0767e3b530e810ce",
          "sha256": "b94b4354cdf26c404c6d9315585b733084b897acc7d0799006509d5293e51b90",
          "sha1": "9a116895920459d7c40b9278fc81c48f5d515660",
          "md5": "394e797c72263afa52f8918d3e82ac45"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-utils-iosarm64-0.25.6-metadata.jar",
          "url": "dynamics-utils-iosarm64-0.25.6-metadata.jar",
          "size": 3253,
          "sha512": "3aff25990a6782f53660eec28c741eeb4495669c048c2f5e95b8d9569da23cbbc71ab071cd48f26bbb54caf441178993d99cce2200c172cb50ee5e099cf7133a",
          "sha256": "f3f2056bbf029833d0a42356ba93bf49a0488ea0c16c2ee12a4493ca0cda8e15",
          "sha1": "c4625cacca407a2e7d7b0dc7020008588e3aba39",
          "md5": "2e8bf98e6e1289d8c401f27bbf95b34d"
        }
      ]
    }
  ]
}
