{
  "formatVersion": "1.1",
  "component": {
    "url": "../../exceptions/0.8.0/exceptions-0.8.0.module",
    "group": "com.riseworld.launchpad.kable-fork",
    "module": "exceptions",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "exceptions-iosArm64Main-0.8.0.klib",
          "url": "exceptions-iosarm64-0.8.0.klib",
          "size": 15434,
          "sha512": "8a310ec9d07ac7b723f19a8c203637f2cd3b4cac9cca2ce9424d16419452db8c7382a83e9faff32e8556279783637b9ee7ccccd87e39e54ae34f5eb245637f50",
          "sha256": "96533d211e924a3ec7f9db90fe65d024b016713492c6c950b00c72b4cf9483ac",
          "sha1": "313675092ead8e2cf886defe900906a38931e38b",
          "md5": "bbede2922c1b8b6b5acc6bb17156a947"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "exceptions-iosarm64-0.8.0-metadata.jar",
          "url": "exceptions-iosarm64-0.8.0-metadata.jar",
          "size": 3303,
          "sha512": "384291963296948a57a58fed2b1fcbbc8365552ac6bd119b35455a90e136fa6cd67d3694fe4478b4e58e793c5069841cf4b73c3926a74f63fa2446bff805d21e",
          "sha256": "b487069979cba4b2ebd24647a188ffdf7ad5b164e98fd163bc92ed8d40875ab5",
          "sha1": "e096d41cc6dfd8e60d18ec6513199be76e3f78a4",
          "md5": "b1675248a0994e31ac446ecbe37afb90"
        }
      ]
    }
  ]
}
