{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-ble-utils/0.25.6/dynamics-ble-utils-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-ble-utils",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-utils-jvm-0.25.6.jar",
          "url": "dynamics-ble-utils-jvm-0.25.6.jar",
          "size": 39530,
          "sha512": "b0bcc8e100ca9f4068fa5da01c0a3e3973445b02689140aef2ca1502f7c4fa956791090035afe36a02eade87f6a973475f933188c5e31149754956ada376e505",
          "sha256": "0783c7d89d3cc4ffc239246d0d7145235570994208441fed214239b0efa5861e",
          "sha1": "cc256c143bca884f0891bc3a7bd02d37f9e9bafe",
          "md5": "6f57c41a3dca11f10d17f1f51c1bfc01"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-utils-jvm-0.25.6.jar",
          "url": "dynamics-ble-utils-jvm-0.25.6.jar",
          "size": 39530,
          "sha512": "b0bcc8e100ca9f4068fa5da01c0a3e3973445b02689140aef2ca1502f7c4fa956791090035afe36a02eade87f6a973475f933188c5e31149754956ada376e505",
          "sha256": "0783c7d89d3cc4ffc239246d0d7145235570994208441fed214239b0efa5861e",
          "sha1": "cc256c143bca884f0891bc3a7bd02d37f9e9bafe",
          "md5": "6f57c41a3dca11f10d17f1f51c1bfc01"
        }
      ]
    }
  ]
}
