{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-constants/0.25.6/dynamics-constants-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-constants",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-constants-iosSimulatorArm64Main-0.25.6.klib",
          "url": "dynamics-constants-iossimulatorarm64-0.25.6.klib",
          "size": 41628,
          "sha512": "0cb93a64a6f543d1bef878bbf6cd1290b54cd30844b17bfa22883523dd7557f4aa209c93f0e9bd8972566aa75efa908a8ba8be87d63e74457841ab94ea4ace7e",
          "sha256": "96876ddc45cc6a33910a9360e29161a606411764be538ff9fbbac25c140973b2",
          "sha1": "ad19a5860bfc772cc372d8f4895a4a679742ff6e",
          "md5": "d754b9a06dd5b7167efb3c53a6ac4b1e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-constants-iossimulatorarm64-0.25.6-metadata.jar",
          "url": "dynamics-constants-iossimulatorarm64-0.25.6-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
