{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-models/0.25.6/dynamics-models-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-models",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-iosArm64Main-0.25.6.klib",
          "url": "dynamics-models-iosarm64-0.25.6.klib",
          "size": 333758,
          "sha512": "0058e4e4bd493db85a15f12d2feee38ca7bdf278f0ab2ad1451150b03bc4bd2077653431be50f5730b2cd8ffe777e4d337f7ab005586579f8adc159c7dd5a3fc",
          "sha256": "3653e66fa9b56043b3da4ba429f12d0773e2fe8900ce709f443b41046fdae3a5",
          "sha1": "e84683f783ff1bcf3c8b536115a689529a5a9763",
          "md5": "5642a8963139724e3893da0e05331e23"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-iosarm64-0.25.6-metadata.jar",
          "url": "dynamics-models-iosarm64-0.25.6-metadata.jar",
          "size": 9288,
          "sha512": "3e546bbfeb0691c4ec863a99e3896789a8f0cf7e1ac3ef37094240fb9d5b77c46b8a24f923503c92311fd929b223c4c5bfe2008efe89cad4e6bb0a985dde6e4d",
          "sha256": "9214dfa86ed3d2bd21b46866a7ff3267dce7e4fe441bae73a9ed58ea75985fa2",
          "sha1": "54ccaa348e0c092cdcf45cce87cadf3580b77e7d",
          "md5": "a70be39a68b521e4f40790acbacc1dc5"
        }
      ]
    }
  ]
}
