{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-utils/0.25.6/dynamics-utils-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-utils",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-utils.aar",
          "url": "dynamics-utils-android-0.25.6.aar",
          "size": 43031,
          "sha512": "33bc0a429d75dbf2c0017876ea493f4afe4a988f1b505693675a8355a50e2ce68901aa2c4d981c1d0e364f760f8380ad88d4e53f3c057ed5631b72dea035fc19",
          "sha256": "1832a7d4c8b55bb68a4effcd276c6ad1f7b89294e0857ec9df11834d03d6d66a",
          "sha1": "4560e6701b29f002afe8ce5b4ff9b859dd0133d0",
          "md5": "852c34b7cf53d2abccbb121aa039ea3f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-utils.aar",
          "url": "dynamics-utils-android-0.25.6.aar",
          "size": 43031,
          "sha512": "33bc0a429d75dbf2c0017876ea493f4afe4a988f1b505693675a8355a50e2ce68901aa2c4d981c1d0e364f760f8380ad88d4e53f3c057ed5631b72dea035fc19",
          "sha256": "1832a7d4c8b55bb68a4effcd276c6ad1f7b89294e0857ec9df11834d03d6d66a",
          "sha1": "4560e6701b29f002afe8ce5b4ff9b859dd0133d0",
          "md5": "852c34b7cf53d2abccbb121aa039ea3f"
        }
      ]
    }
  ]
}
