{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-io/0.25.6/dynamics-io-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-io",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-io-jvm-0.25.6.jar",
          "url": "dynamics-io-jvm-0.25.6.jar",
          "size": 207933,
          "sha512": "b4b819a6d5e394099dc4a781f3fb85652bd733d5eb9806b77f8b3da0fa330a9517b76ef12419564de20dab51479b404e78a7745ab40632e6f0fbad8f1ca8528d",
          "sha256": "fd853344abb44ddfb305bf77297f89df1ce709ef419337de7ab0f597dbd0192c",
          "sha1": "e1764832ac228d62827c3c51ecb63110daf6b62f",
          "md5": "5f865350568676004d6f84ab5b0af423"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-serialization-csv",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-ble-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-io-jvm-0.25.6.jar",
          "url": "dynamics-io-jvm-0.25.6.jar",
          "size": 207933,
          "sha512": "b4b819a6d5e394099dc4a781f3fb85652bd733d5eb9806b77f8b3da0fa330a9517b76ef12419564de20dab51479b404e78a7745ab40632e6f0fbad8f1ca8528d",
          "sha256": "fd853344abb44ddfb305bf77297f89df1ce709ef419337de7ab0f597dbd0192c",
          "sha1": "e1764832ac228d62827c3c51ecb63110daf6b62f",
          "md5": "5f865350568676004d6f84ab5b0af423"
        }
      ]
    }
  ]
}
