{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ble-multiplex/0.24.0/ble-multiplex-0.24.0.module",
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-iosArm64Main-0.24.0.klib",
          "url": "ble-multiplex-iosarm64-0.24.0.klib",
          "size": 113832,
          "sha512": "8bdb369bad813b84d0d949d00f9be89987ec27cdcfdd56118884d913108908df73d48306246cc7836a584c51c7c8604ac376d055455ab474ba4a0f0ed022ed17",
          "sha256": "443036c8f43b94e7aa9f182c0d24ebfda5c8c24f446b0192f7bd3b59ce8e630d",
          "sha1": "69904bf8b73e200bacb76207bbd393930403ba52",
          "md5": "c59655b7acdd9169363408e2353eef50"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-iosarm64-0.24.0-metadata.jar",
          "url": "ble-multiplex-iosarm64-0.24.0-metadata.jar",
          "size": 3696,
          "sha512": "008def464738a7a2fe62c5824eccb82f398177146ece3000aa069a67ea00decbce9749cb01aef8812d4baed2a1a2c9a2aabeef1060c09a8c36e89436d993a35c",
          "sha256": "cf3233e101840b21f3f5026755320d58188deeaea456ef2ace7f8c18cabd2e54",
          "sha1": "9b62b9a3377ad38a94615a8d76ab880dba1a9adb",
          "md5": "2dbc2714b0bffa68dc1479670762ab24"
        }
      ]
    }
  ]
}
