{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-models-composite/0.25.6/dynamics-models-composite-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-models-composite",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-composite-iosX64Main-0.25.6.klib",
          "url": "dynamics-models-composite-iosx64-0.25.6.klib",
          "size": 41238,
          "sha512": "2120d5951a343386c15ca5eb48604efe52db12b24a84622d84a195baf35d978a3400636afe8cb03f689c1b1325edf237d7d39682b858607d28477709bbc29c6a",
          "sha256": "61f508f7c729abcdba9bfe0b717cd4b851b31c717e0f48af7ada9a93e472f585",
          "sha1": "fdd6b819d8510aaa9482cc4d21fdc9883be897e5",
          "md5": "402723866183d899a5f78411126a647c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-composite-iosx64-0.25.6-metadata.jar",
          "url": "dynamics-models-composite-iosx64-0.25.6-metadata.jar",
          "size": 2826,
          "sha512": "981b9ed906b9efe5a17217dd7eccd0a17713af99c9e08952d060ac4fd73b7a53a891bd725c6534d3d01cf8edc24765a83f3b3609ae6700602d1f55daffffb142",
          "sha256": "03ef834b77637cbb540fb97cef5e872bd9dae9400ff82b85cb0b1ec84cc0f172",
          "sha1": "45b4ce3a28e3d353e9f98ebfb9fa7ecf0810ad95",
          "md5": "cd4d8cf7d627005bab9e35ebfb9baa0c"
        }
      ]
    }
  ]
}
