{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.8.0/core-0.8.0.module",
    "group": "com.riseworld.launchpad.kable-fork",
    "module": "core",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "models",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "com.juul.tuulbox",
          "module": "collections",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.8.0.klib",
          "url": "core-iosx64-0.8.0.klib",
          "size": 235524,
          "sha512": "8739b855d8b232de4ceee0a7639bafdbafe1928b7e0c3104ec60a79dbfcb5de32f0080b0d820baefed37a3b8193485ed23e8fef3dc0b191c8ab22edef2538cf4",
          "sha256": "44521032dd81ca26cc5c45e99e47347f6c73dae95788ba51e27292c5ab076f4d",
          "sha1": "203761d81bef19981fedb444a1194b8fbbea21ec",
          "md5": "8ebb520d6808c99ed1b363f5d6c8d3b2"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "models",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "com.juul.tuulbox",
          "module": "collections",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.8.0-metadata.jar",
          "url": "core-iosx64-0.8.0-metadata.jar",
          "size": 24427,
          "sha512": "089846deb94e57de6928da60bfdab90d328ea4cfa6ff833e82b23975f81f6d46723a3678892df30b0c409ab365cc56ff439374ec1668f167f8f472967c45ed68",
          "sha256": "809fc1ac366cb757788e1387a9f12089df053b4a237f64929b8004401e0d9bae",
          "sha1": "b3231b9a878023e9eb27e3823cec35ffd76022d8",
          "md5": "85a5d5caa153e1eb771558ce10db7157"
        }
      ]
    }
  ]
}
