{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-ble-utils/0.25.6/dynamics-ble-utils-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-ble-utils",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-utils.aar",
          "url": "dynamics-ble-utils-android-0.25.6.aar",
          "size": 25671,
          "sha512": "4d5f45299fdc3819f8ba62eed7307d00203a0582cb2d83f198567c85eee154bc190db71001563ba82e17617f130e706746ef3ee27cd979c1940b4bf298ce79e5",
          "sha256": "76d8ad349fcbe9b92fc477fde596f3e41e937bfc6620ef3ad51468d081215f1c",
          "sha1": "95c9deb42fee5e13fbde880f71d1c0608732e13d",
          "md5": "14e9524a83a5ddef989f4707a3778e64"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-utils.aar",
          "url": "dynamics-ble-utils-android-0.25.6.aar",
          "size": 25671,
          "sha512": "4d5f45299fdc3819f8ba62eed7307d00203a0582cb2d83f198567c85eee154bc190db71001563ba82e17617f130e706746ef3ee27cd979c1940b4bf298ce79e5",
          "sha256": "76d8ad349fcbe9b92fc477fde596f3e41e937bfc6620ef3ad51468d081215f1c",
          "sha1": "95c9deb42fee5e13fbde880f71d1c0608732e13d",
          "md5": "14e9524a83a5ddef989f4707a3778e64"
        }
      ]
    }
  ]
}
