{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-ble-utils/0.25.6/dynamics-ble-utils-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-ble-utils",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-utils-iosSimulatorArm64Main-0.25.6.klib",
          "url": "dynamics-ble-utils-iossimulatorarm64-0.25.6.klib",
          "size": 42320,
          "sha512": "34115e4c6291266ed7e5b99fb67a422822d7e925a2c6af055f05020ac00042f6f01e1d57920822d846ef0b42b4a5ffffc906d171b6516e98aab80778087404a3",
          "sha256": "e4f8f046e645336f3ce20d571d171131d9ed9c693b95457f8f26b3d42d0c0858",
          "sha1": "97373bc340580319c2f1ac94f05ce8dd2ade7e31",
          "md5": "4e9ec23b3a1ce153327da5c95427ddef"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-utils-iossimulatorarm64-0.25.6-metadata.jar",
          "url": "dynamics-ble-utils-iossimulatorarm64-0.25.6-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
