{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ble-multiplex-models/0.24.0/ble-multiplex-models-0.24.0.module",
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex-models",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-models-iosSimulatorArm64Main-0.24.0.klib",
          "url": "ble-multiplex-models-iossimulatorarm64-0.24.0.klib",
          "size": 77510,
          "sha512": "b190b72c4ff76e53035c26e1c3622f6ace1b00a6445b77ce789e793972a64270c416d2f7ddf5a2bad18ef6e58ae29e81367a9ce24cb0797610b40ff50370fabc",
          "sha256": "5f069cd449f1e8680eb44d747c9da801a8e7b00281021694e9f71fd649bb14aa",
          "sha1": "cc62c9e02777941a29a5c6f7f4ae76660cef1571",
          "md5": "69d896217b86853e055699afb0e945c2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-models-iossimulatorarm64-0.24.0-metadata.jar",
          "url": "ble-multiplex-models-iossimulatorarm64-0.24.0-metadata.jar",
          "size": 3190,
          "sha512": "ab629548e4cc8493a4584e042cafc2af00e69ad0de48f536be7807a645cc3d891b715c0eded3de3505cb56dc61d66d7910dcc89ff097ab7072e9f7563ff7a19c",
          "sha256": "cd085df0732d55492edffc7090c13c4776370fadea3234e40ba769424125af81",
          "sha1": "5bcba9cdad6403f5d8b0615958dc8e7f95005da8",
          "md5": "79a213948b4811f8b295259773cb0192"
        }
      ]
    }
  ]
}
