{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ble-multiplex/0.24.0/ble-multiplex-0.24.0.module",
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-iosX64Main-0.24.0.klib",
          "url": "ble-multiplex-iosx64-0.24.0.klib",
          "size": 113820,
          "sha512": "c5719c697bcccf5fde4cc29703e3a6cb9642cb1d28b17672a0e23de22d4d6b80e4725111be2afc10d8eae06833204ecba8eb8b4d322ccba61b4247d5ba70fdf7",
          "sha256": "14012fbcc407be33250c8c8aad72555d2f3e4d28ee42f00ecd22220dfb97579e",
          "sha1": "9b2e3c0ce2f9a1d4c5467fe7ee3b590c62b49cb3",
          "md5": "425a05c7d81c07a8918c82e565f791cb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-iosx64-0.24.0-metadata.jar",
          "url": "ble-multiplex-iosx64-0.24.0-metadata.jar",
          "size": 3696,
          "sha512": "008def464738a7a2fe62c5824eccb82f398177146ece3000aa069a67ea00decbce9749cb01aef8812d4baed2a1a2c9a2aabeef1060c09a8c36e89436d993a35c",
          "sha256": "cf3233e101840b21f3f5026755320d58188deeaea456ef2ace7f8c18cabd2e54",
          "sha1": "9b62b9a3377ad38a94615a8d76ab880dba1a9adb",
          "md5": "2dbc2714b0bffa68dc1479670762ab24"
        }
      ]
    }
  ]
}
