{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-math/0.25.6/dynamics-math-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-math",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-math-iosArm64Main-0.25.6.klib",
          "url": "dynamics-math-iosarm64-0.25.6.klib",
          "size": 68587,
          "sha512": "74a57f6d603d6f4cfcf0c05c3a81a58a962d0b4a22c1cec39a09ca8e08175bbbe7772b50e6050918aaa3a86ec4e1ee22b7c33a61fa97f02c6b57319ebc24293b",
          "sha256": "99196b6c2479f99e0bbbdd94b571831a64b010bf75ce38a0a752e2f1ea87ae90",
          "sha1": "cff3401dccfd2ecf67858fc94ab272ae68d48460",
          "md5": "00ac599353d18a4623159df450c9bc02"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-math-iosarm64-0.25.6-metadata.jar",
          "url": "dynamics-math-iosarm64-0.25.6-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
