{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-models-composite/0.25.6/dynamics-models-composite-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-models-composite",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-composite-iosArm64Main-0.25.6.klib",
          "url": "dynamics-models-composite-iosarm64-0.25.6.klib",
          "size": 41251,
          "sha512": "128364d6bea5d6509da5722f9b5b503b88c3cf38d134feaaf5b02925f6e0af7f9f0e1001fa5571ee18e513cd602eac477fd0b0071b482da044270250e9615371",
          "sha256": "9fdb753614f6f668dbf2ce349d31840f925f76fbd09129ddf5d0270004a472e0",
          "sha1": "2bf9a7f1d053ed33ab7eeeff84bfbe1347799e56",
          "md5": "e3c0604cdf6d8f5f5d1d576000a95f93"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-composite-iosarm64-0.25.6-metadata.jar",
          "url": "dynamics-models-composite-iosarm64-0.25.6-metadata.jar",
          "size": 2826,
          "sha512": "981b9ed906b9efe5a17217dd7eccd0a17713af99c9e08952d060ac4fd73b7a53a891bd725c6534d3d01cf8edc24765a83f3b3609ae6700602d1f55daffffb142",
          "sha256": "03ef834b77637cbb540fb97cef5e872bd9dae9400ff82b85cb0b1ec84cc0f172",
          "sha1": "45b4ce3a28e3d353e9f98ebfb9fa7ecf0810ad95",
          "md5": "cd4d8cf7d627005bab9e35ebfb9baa0c"
        }
      ]
    }
  ]
}
