{
  "formatVersion": "1.1",
  "component": {
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-ble-utils",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-ble-utils-metadata-0.25.6.jar",
          "url": "dynamics-ble-utils-0.25.6.jar",
          "size": 4795,
          "sha512": "53c73c0e5ba1c554cd4357be6a843a62ef4cf762b938f1d41e20b28924f936912f7dfdb711bf6a938f92a35cb790a82cb998a219c0603ff76697c1e6c4225e13",
          "sha256": "420fe3d75ace8eb8518f07532722e0841ab3a9958ef0ae8f08014518671432d3",
          "sha1": "097d1602952b67d9bd526b9d74d7025c2a36e162",
          "md5": "6dfeaafd5eefdc0c44cb9a0d06707ba9"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-android/0.25.6/dynamics-ble-utils-android-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-android",
        "version": "0.25.6"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-android/0.25.6/dynamics-ble-utils-android-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-android",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-iosarm64/0.25.6/dynamics-ble-utils-iosarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-iosarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-iosarm64/0.25.6/dynamics-ble-utils-iosarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-iosarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-iossimulatorarm64/0.25.6/dynamics-ble-utils-iossimulatorarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-iossimulatorarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-iossimulatorarm64/0.25.6/dynamics-ble-utils-iossimulatorarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-iossimulatorarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-iosx64/0.25.6/dynamics-ble-utils-iosx64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-iosx64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-iosx64/0.25.6/dynamics-ble-utils-iosx64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-iosx64",
        "version": "0.25.6"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-jvm/0.25.6/dynamics-ble-utils-jvm-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-jvm",
        "version": "0.25.6"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../dynamics-ble-utils-jvm/0.25.6/dynamics-ble-utils-jvm-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-ble-utils-jvm",
        "version": "0.25.6"
      }
    }
  ]
}
