{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-models/0.25.6/dynamics-models-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-models",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-jvm-0.25.6.jar",
          "url": "dynamics-models-jvm-0.25.6.jar",
          "size": 356033,
          "sha512": "28544f5ae59a5d654decd93a5f9217f5c187d2426f68863be47d23245a402aaa9656c9112e78f94eb4e9e1cdc0e77c8a76d342aa6ee2dfc816f5ca48a95f8d1d",
          "sha256": "8f9da5dc807299d04f1f39a2b8e5f3895e840da7fad1d8e5b2b76bdb58fe5a8e",
          "sha1": "a5fec805aee0b4c11d902f9aab26e1bfd9e9192d",
          "md5": "034f598c0d91a99e254a8bd3078e5215"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-jvm-0.25.6.jar",
          "url": "dynamics-models-jvm-0.25.6.jar",
          "size": 356033,
          "sha512": "28544f5ae59a5d654decd93a5f9217f5c187d2426f68863be47d23245a402aaa9656c9112e78f94eb4e9e1cdc0e77c8a76d342aa6ee2dfc816f5ca48a95f8d1d",
          "sha256": "8f9da5dc807299d04f1f39a2b8e5f3895e840da7fad1d8e5b2b76bdb58fe5a8e",
          "sha1": "a5fec805aee0b4c11d902f9aab26e1bfd9e9192d",
          "md5": "034f598c0d91a99e254a8bd3078e5215"
        }
      ]
    }
  ]
}
