{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-models-composite/0.25.6/dynamics-models-composite-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-models-composite",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-composite-iosSimulatorArm64Main-0.25.6.klib",
          "url": "dynamics-models-composite-iossimulatorarm64-0.25.6.klib",
          "size": 41317,
          "sha512": "fda628e20ad29dff1b4b818bdcd7f9548bfd3c90094273a112ce86a91e1803d112a6d594358016b0adbcfa03cbb51c66ca68efbaa20ed9aeae99043bdd05efd3",
          "sha256": "eeb2f9a1bbc9abc9654b177d044e5997b936334b15145f97cbabd5ae17c64236",
          "sha1": "ce2aaa552fa7f24a2c6976a2b6d82655c0640a8f",
          "md5": "1dab30d61db8775af06976f62c12ee4e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-composite-iossimulatorarm64-0.25.6-metadata.jar",
          "url": "dynamics-models-composite-iossimulatorarm64-0.25.6-metadata.jar",
          "size": 2826,
          "sha512": "981b9ed906b9efe5a17217dd7eccd0a17713af99c9e08952d060ac4fd73b7a53a891bd725c6534d3d01cf8edc24765a83f3b3609ae6700602d1f55daffffb142",
          "sha256": "03ef834b77637cbb540fb97cef5e872bd9dae9400ff82b85cb0b1ec84cc0f172",
          "sha1": "45b4ce3a28e3d353e9f98ebfb9fa7ecf0810ad95",
          "md5": "cd4d8cf7d627005bab9e35ebfb9baa0c"
        }
      ]
    }
  ]
}
