{
  "formatVersion": "1.1",
  "component": {
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex-models",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-models-metadata-0.24.0.jar",
          "url": "ble-multiplex-models-0.24.0.jar",
          "size": 22187,
          "sha512": "57986a636d295522eea69e865fa8adf4dd6b62f1318bc64b2c1aadcd00088809a5dfe548433ae81935adf3875d12e2b0d197b9d788964c805096522eece60abe",
          "sha256": "3de24baffc872d2f4e5c03f87d26eedbcd118788d3d21e21ebe2cf57554a7715",
          "sha1": "20164e572f13a01fe6c86cd369ea085325fda423",
          "md5": "8dc9f61c6375e616d980d4171594970e"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-android/0.24.0/ble-multiplex-models-android-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-android",
        "version": "0.24.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-android/0.24.0/ble-multiplex-models-android-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-android",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-iosarm64/0.24.0/ble-multiplex-models-iosarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-iosarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-iosarm64/0.24.0/ble-multiplex-models-iosarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-iosarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-iossimulatorarm64/0.24.0/ble-multiplex-models-iossimulatorarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-iossimulatorarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-iossimulatorarm64/0.24.0/ble-multiplex-models-iossimulatorarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-iossimulatorarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-iosx64/0.24.0/ble-multiplex-models-iosx64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-iosx64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-models-iosx64/0.24.0/ble-multiplex-models-iosx64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-models-iosx64",
        "version": "0.24.0"
      }
    }
  ]
}
