{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ble-multiplex/0.24.0/ble-multiplex-0.24.0.module",
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex.aar",
          "url": "ble-multiplex-android-0.24.0.aar",
          "size": 170847,
          "sha512": "035d5beefc47776a592602b857894fbd3a450e29facbfe50011d3d8ab3135809da2434bb46e302d160a71b8391f63f25c85eb619254a988ef7c64352d2501c50",
          "sha256": "60b975f4b5e0b47571787bc37f2a9c79e70fa9ddeba4641ddf95f0d57b1c30cb",
          "sha1": "a9d580aae47d1737596ece12acd6cf733d9191bf",
          "md5": "7fa8eb159577c48ace7adf23219dba59"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-models",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex.aar",
          "url": "ble-multiplex-android-0.24.0.aar",
          "size": 170847,
          "sha512": "035d5beefc47776a592602b857894fbd3a450e29facbfe50011d3d8ab3135809da2434bb46e302d160a71b8391f63f25c85eb619254a988ef7c64352d2501c50",
          "sha256": "60b975f4b5e0b47571787bc37f2a9c79e70fa9ddeba4641ddf95f0d57b1c30cb",
          "sha1": "a9d580aae47d1737596ece12acd6cf733d9191bf",
          "md5": "7fa8eb159577c48ace7adf23219dba59"
        }
      ]
    }
  ]
}
