{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-db/0.25.6/dynamics-db-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-db",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-db.aar",
          "url": "dynamics-db-android-0.25.6.aar",
          "size": 345421,
          "sha512": "043e3a1b902cf4930a1863eb8ffcdcc2ca106ad29f8db17d77ee009d3e9cb3857cdc84e2d28d918cda58973d084aebe2949bdda767fcdee75637d92cc61e0ebf",
          "sha256": "760eefecd9d561ae461664ef8d4715f9c1316062a24c38b133300d20dbd2f1fa",
          "sha1": "0b539d385d213496ae5d5ce97ebe239660949b76",
          "md5": "cba1873712938fac615e731831095454"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-db.aar",
          "url": "dynamics-db-android-0.25.6.aar",
          "size": 345421,
          "sha512": "043e3a1b902cf4930a1863eb8ffcdcc2ca106ad29f8db17d77ee009d3e9cb3857cdc84e2d28d918cda58973d084aebe2949bdda767fcdee75637d92cc61e0ebf",
          "sha256": "760eefecd9d561ae461664ef8d4715f9c1316062a24c38b133300d20dbd2f1fa",
          "sha1": "0b539d385d213496ae5d5ce97ebe239660949b76",
          "md5": "cba1873712938fac615e731831095454"
        }
      ]
    }
  ]
}
