{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-constants/0.25.6/dynamics-constants-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-constants",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-constants-iosArm64Main-0.25.6.klib",
          "url": "dynamics-constants-iosarm64-0.25.6.klib",
          "size": 41562,
          "sha512": "75002204d1ba619684e7c724c10ca72f8bfd6f55a807a3191cd17926423b678a38d4756dd4820a5dd70bb71e05248ca7f392c81946e5f35ba49418bc0bc04985",
          "sha256": "18434b0159bd8d0a3202a5d8d845df6a3b90c7f301f47e463a0b81c39b8b5dce",
          "sha1": "b546e410f5a41a19b1c3f96543df7e6cfe63593f",
          "md5": "c997f66166cd2c13ca23eee2c04ebd81"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-constants-iosarm64-0.25.6-metadata.jar",
          "url": "dynamics-constants-iosarm64-0.25.6-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
