{
  "formatVersion": "1.1",
  "component": {
    "url": "../../exceptions/0.8.0/exceptions-0.8.0.module",
    "group": "com.riseworld.launchpad.kable-fork",
    "module": "exceptions",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "exceptions-macosArm64Main-0.8.0.klib",
          "url": "exceptions-macosarm64-0.8.0.klib",
          "size": 15447,
          "sha512": "d4d8b7f149ed58bb0430d603e44b68fddc7a2d709c1e14a47d051a5bc404b6200e0464add0aeae31cc14d0efea998efd2fb6c0f64b9f6d54f55952af35699a94",
          "sha256": "7e69f61f4be01f2e8c2d6afdd9e242bad35eebcffc32e00188016a4bbe01bd69",
          "sha1": "7e4cf4d4dd0be43fee4cdb59811be60246929988",
          "md5": "f581b3f145ba16f7b7ab92753497b0c8"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "exceptions-macosarm64-0.8.0-metadata.jar",
          "url": "exceptions-macosarm64-0.8.0-metadata.jar",
          "size": 3303,
          "sha512": "384291963296948a57a58fed2b1fcbbc8365552ac6bd119b35455a90e136fa6cd67d3694fe4478b4e58e793c5069841cf4b73c3926a74f63fa2446bff805d21e",
          "sha256": "b487069979cba4b2ebd24647a188ffdf7ad5b164e98fd163bc92ed8d40875ab5",
          "sha1": "e096d41cc6dfd8e60d18ec6513199be76e3f78a4",
          "md5": "b1675248a0994e31ac446ecbe37afb90"
        }
      ]
    }
  ]
}
