{
  "formatVersion": "1.1",
  "component": {
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-math",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-math-metadata-0.25.6.jar",
          "url": "dynamics-math-0.25.6.jar",
          "size": 11264,
          "sha512": "7de845411a08bb88b0e9908defb230da15b04ed9139833da5db6020c715632aae6cbbc85804e0ee95b6661a5082530fe44b0c2d94aa2f6bc2bf0a8a18353101f",
          "sha256": "673309fb1277a4edc97856fd9b16e1b5e24eb24b59cb3433b3279b938be9d75e",
          "sha1": "fc7e27974474401a8308da7c18eab17acb076db4",
          "md5": "fad771d4de63abeb871addf399c4483e"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../dynamics-math-android/0.25.6/dynamics-math-android-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-android",
        "version": "0.25.6"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../dynamics-math-android/0.25.6/dynamics-math-android-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-android",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-math-iosarm64/0.25.6/dynamics-math-iosarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-iosarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-math-iosarm64/0.25.6/dynamics-math-iosarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-iosarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-math-iossimulatorarm64/0.25.6/dynamics-math-iossimulatorarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-iossimulatorarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-math-iossimulatorarm64/0.25.6/dynamics-math-iossimulatorarm64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-iossimulatorarm64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-math-iosx64/0.25.6/dynamics-math-iosx64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-iosx64",
        "version": "0.25.6"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../dynamics-math-iosx64/0.25.6/dynamics-math-iosx64-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-iosx64",
        "version": "0.25.6"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../dynamics-math-jvm/0.25.6/dynamics-math-jvm-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-jvm",
        "version": "0.25.6"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../dynamics-math-jvm/0.25.6/dynamics-math-jvm-0.25.6.module",
        "group": "com.riseworld.dynamics.multiplatform",
        "module": "dynamics-math-jvm",
        "version": "0.25.6"
      }
    }
  ]
}
