{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ble-multiplex-models/0.24.0/ble-multiplex-models-0.24.0.module",
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex-models",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-models-iosArm64Main-0.24.0.klib",
          "url": "ble-multiplex-models-iosarm64-0.24.0.klib",
          "size": 77444,
          "sha512": "b6470019fc71f600d6f9f0b35341e63154b0661ba6d097f241835ce40485cc0d61814794031bab2a79330c36ccae9a73f7abe705605b0dd738e34e5e5d33395f",
          "sha256": "d4dcd1292bdc894664cbc50ec1bd2f66c246fbf6e4ecd3447872ac4bfc3ef953",
          "sha1": "a5e3640db91592ffc6e62d9fe73ad0e3aa5dc471",
          "md5": "19a0be5dbd66e72828521f9f82dcc293"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-models-iosarm64-0.24.0-metadata.jar",
          "url": "ble-multiplex-models-iosarm64-0.24.0-metadata.jar",
          "size": 3190,
          "sha512": "ab629548e4cc8493a4584e042cafc2af00e69ad0de48f536be7807a645cc3d891b715c0eded3de3505cb56dc61d66d7910dcc89ff097ab7072e9f7563ff7a19c",
          "sha256": "cd085df0732d55492edffc7090c13c4776370fadea3234e40ba769424125af81",
          "sha1": "5bcba9cdad6403f5d8b0615958dc8e7f95005da8",
          "md5": "79a213948b4811f8b295259773cb0192"
        }
      ]
    }
  ]
}
