-keep class com.boxreha.dynamics.DynamicsUnityBridge { public static *; }
-keep class com.boxreha.dynamics.DynamicsPermissionFragment { *; }
# Exact classes accessed by the SDK 0.25.6 ABI adapter. Retain public mangled method names.
-keep class com.riseworld.dynamics.models.PeripheralDto { public *; }
-keep class com.riseworld.dynamics.models.PeripheralId { public *; }
-keep class com.riseworld.dynamics.models.domain.punch.Punch { public *; }
-keep class com.riseworld.dynamics.models.domain.punch.Speed { public *; }
-keep class com.riseworld.dynamics.models.domain.profile.body.BodyProfile { public *; }
-keep class com.riseworld.dynamics.models.ble.data.SensorDataPacket { public *; }
-keep class com.riseworld.dynamics.multiplatform.repository.GloveRepository { public *; }
-keep class com.riseworld.dynamics.multiplatform.repository.SensorDataRepository { public *; }
-keep class com.riseworld.dynamics.multiplatform.repository.PairingRepository { public *; }
-keep class kotlin.time.Duration { public *; }
