{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-io/0.25.6/dynamics-io-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-io",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-io.aar",
          "url": "dynamics-io-android-0.25.6.aar",
          "size": 174028,
          "sha512": "9d8582e096ea30ee523e1d9183cd9238f7f5be55dac9d00386a7c5319e9784a7e35f5ea563f07d359154dc605f114d30c2125ff1c47147fb0440d722d51bab07",
          "sha256": "54cd00c754a0d3399a9c512675c7ba91dd9cee3f4c78be6063fa16e3227cc508",
          "sha1": "f8be695027e5d2f9931cbc9984a313e99c3f8497",
          "md5": "02840252f859d785ae047a0f1eda7604"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-serialization-csv",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-models",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-ble-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-math",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-io.aar",
          "url": "dynamics-io-android-0.25.6.aar",
          "size": 174028,
          "sha512": "9d8582e096ea30ee523e1d9183cd9238f7f5be55dac9d00386a7c5319e9784a7e35f5ea563f07d359154dc605f114d30c2125ff1c47147fb0440d722d51bab07",
          "sha256": "54cd00c754a0d3399a9c512675c7ba91dd9cee3f4c78be6063fa16e3227cc508",
          "sha1": "f8be695027e5d2f9931cbc9984a313e99c3f8497",
          "md5": "02840252f859d785ae047a0f1eda7604"
        }
      ]
    }
  ]
}
