{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource/2.12.0/resource-2.12.0.module",
    "group": "com.riseworld.launchpad.resource",
    "module": "resource",
    "version": "2.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-iosSimulatorArm64Main-2.12.0.klib",
          "url": "resource-iossimulatorarm64-2.12.0.klib",
          "size": 13822,
          "sha512": "c7bea7e938ed026d68130149f055ef88929ede41837ac12a2931619790bdd7882851f3058fd132b5f56074c3a8c12b5b5f848caffde0b8e34b9ecd906e01e765",
          "sha256": "d103dbebed260f459751eacc0a4bff76a12c14396588882e20cfd86878094c73",
          "sha1": "551e0695791f4e988e9cf5fd3cf3f9717912173a",
          "md5": "f24a0fd7a2470752b4046785bbbba6f8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-iossimulatorarm64-2.12.0-metadata.jar",
          "url": "resource-iossimulatorarm64-2.12.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
