{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ble-multiplex-models/0.24.0/ble-multiplex-models-0.24.0.module",
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex-models",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-models.aar",
          "url": "ble-multiplex-models-android-0.24.0.aar",
          "size": 78305,
          "sha512": "c61a9fbc94f3adf77ce9a9e2a6927c05ef3119d262b4c95e2a712bb86d6c0b4979b8a4e1d89ff934e46fc83ffd30dcd2b5fbb6ea956164795dea178c11ac84ae",
          "sha256": "94b6789918b0a4b7e239e7112b5465c06d67989c0bb698075bed0a3519c60198",
          "sha1": "75729ceac2829f73e0e184b0fb8579dda41fa639",
          "md5": "d0ba9d4c5bca0e682c3169bb561f3041"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.riseworld.launchpad.ble",
          "module": "ble-multiplex-uuid",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.kable-fork",
          "module": "exceptions",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-models.aar",
          "url": "ble-multiplex-models-android-0.24.0.aar",
          "size": 78305,
          "sha512": "c61a9fbc94f3adf77ce9a9e2a6927c05ef3119d262b4c95e2a712bb86d6c0b4979b8a4e1d89ff934e46fc83ffd30dcd2b5fbb6ea956164795dea178c11ac84ae",
          "sha256": "94b6789918b0a4b7e239e7112b5465c06d67989c0bb698075bed0a3519c60198",
          "sha1": "75729ceac2829f73e0e184b0fb8579dda41fa639",
          "md5": "d0ba9d4c5bca0e682c3169bb561f3041"
        }
      ]
    }
  ]
}
