{
  "formatVersion": "1.1",
  "component": {
    "url": "../../exceptions/0.8.0/exceptions-0.8.0.module",
    "group": "com.riseworld.launchpad.kable-fork",
    "module": "exceptions",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "exceptions-iosX64Main-0.8.0.klib",
          "url": "exceptions-iosx64-0.8.0.klib",
          "size": 15422,
          "sha512": "02615879d3dcbf4d514d6a61452029fab125e28d631f2652bfd4b60c787ebd4b925127346885151f4b6bb499064f7e21637a805a1910be8cf30c25d13b542a0c",
          "sha256": "5c383c121c0bd88e6272f42838d249cd95daf7230ae4e977587cd0304fcdaeea",
          "sha1": "53306585c3c22e6e4c8fafc048a2e6bf8414a484",
          "md5": "74291955d8cce485404576a36c560173"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "exceptions-iosx64-0.8.0-metadata.jar",
          "url": "exceptions-iosx64-0.8.0-metadata.jar",
          "size": 3303,
          "sha512": "384291963296948a57a58fed2b1fcbbc8365552ac6bd119b35455a90e136fa6cd67d3694fe4478b4e58e793c5069841cf4b73c3926a74f63fa2446bff805d21e",
          "sha256": "b487069979cba4b2ebd24647a188ffdf7ad5b164e98fd163bc92ed8d40875ab5",
          "sha1": "e096d41cc6dfd8e60d18ec6513199be76e3f78a4",
          "md5": "b1675248a0994e31ac446ecbe37afb90"
        }
      ]
    }
  ]
}
