{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource/2.12.0/resource-2.12.0.module",
    "group": "com.riseworld.launchpad.resource",
    "module": "resource",
    "version": "2.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource.aar",
          "url": "resource-android-2.12.0.aar",
          "size": 6124,
          "sha512": "b07e408e40c4d4b03be3fda91b7b1058b26c0839ed2a3660b55fcb55dd82d30c4a7dada0c7076f3084a285201a0d77c0369754a11cfce007f1a508b6824b0fad",
          "sha256": "92a35aaccd31d8f1018fe72813478b0e1db4f1a4f52b29e49c9ddf9c0dd6ec4e",
          "sha1": "8da5a1dac794e575468de2b5787079a8fb396e09",
          "md5": "20aec675acadc715346fbc7d0aa457e9"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource.aar",
          "url": "resource-android-2.12.0.aar",
          "size": 6124,
          "sha512": "b07e408e40c4d4b03be3fda91b7b1058b26c0839ed2a3660b55fcb55dd82d30c4a7dada0c7076f3084a285201a0d77c0369754a11cfce007f1a508b6824b0fad",
          "sha256": "92a35aaccd31d8f1018fe72813478b0e1db4f1a4f52b29e49c9ddf9c0dd6ec4e",
          "sha1": "8da5a1dac794e575468de2b5787079a8fb396e09",
          "md5": "20aec675acadc715346fbc7d0aa457e9"
        }
      ]
    }
  ]
}
