{
  "formatVersion": "1.1",
  "component": {
    "group": "com.riseworld.launchpad.ble",
    "module": "ble-multiplex-uuid",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "ble-multiplex-uuid-metadata-0.24.0.jar",
          "url": "ble-multiplex-uuid-0.24.0.jar",
          "size": 5775,
          "sha512": "0943e2dbc84693ab467130d3c60065f9a6d42df4ecf45335ce3c77b98eef6d556b3f7df85656303b44e58d8c6ff31c7261abe9ccb2c8e2c833a8164dddbeee44",
          "sha256": "6449378fd9e7f3ee9b7cd4f57b203bc6ca62e6cc86097f9b57d0eb3fc9e80991",
          "sha1": "b07172072817a5d79de16819db89bff6f3f6cb4a",
          "md5": "6d7654d46babebd757f0382ffba5fb99"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ble-multiplex-uuid-kotlin-0.24.0-sources.jar",
          "url": "ble-multiplex-uuid-0.24.0-sources.jar",
          "size": 5312,
          "sha512": "657be5bad06d8b0433e69300e69ff27001dcd011413018b2a35a4a57d114496c4377b9772497451e2b32c63069661ff1adb86e10727307f20b58b66ee225d45f",
          "sha256": "3f65ad2ede237cd17358aa2e1dc55099d37b11aa73b94b6d14b5d3268dff2bc7",
          "sha1": "61a3639d586529d2aef3c1242aa474d154d1f33c",
          "md5": "955ae6eda77fd23bdf3ed218e95728e9"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-android/0.24.0/ble-multiplex-uuid-android-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-android",
        "version": "0.24.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-android/0.24.0/ble-multiplex-uuid-android-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-android",
        "version": "0.24.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-android/0.24.0/ble-multiplex-uuid-android-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-android",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iosarm64/0.24.0/ble-multiplex-uuid-iosarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iosarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iosarm64/0.24.0/ble-multiplex-uuid-iosarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iosarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iosarm64/0.24.0/ble-multiplex-uuid-iosarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iosarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iossimulatorarm64/0.24.0/ble-multiplex-uuid-iossimulatorarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iossimulatorarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iossimulatorarm64/0.24.0/ble-multiplex-uuid-iossimulatorarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iossimulatorarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iossimulatorarm64/0.24.0/ble-multiplex-uuid-iossimulatorarm64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iossimulatorarm64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iosx64/0.24.0/ble-multiplex-uuid-iosx64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iosx64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iosx64/0.24.0/ble-multiplex-uuid-iosx64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iosx64",
        "version": "0.24.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-iosx64/0.24.0/ble-multiplex-uuid-iosx64-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-iosx64",
        "version": "0.24.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-jvm/0.24.0/ble-multiplex-uuid-jvm-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-jvm",
        "version": "0.24.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-jvm/0.24.0/ble-multiplex-uuid-jvm-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-jvm",
        "version": "0.24.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ble-multiplex-uuid-jvm/0.24.0/ble-multiplex-uuid-jvm-0.24.0.module",
        "group": "com.riseworld.launchpad.ble",
        "module": "ble-multiplex-uuid-jvm",
        "version": "0.24.0"
      }
    }
  ]
}
