{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resource/2.12.0/resource-2.12.0.module",
    "group": "com.riseworld.launchpad.resource",
    "module": "resource",
    "version": "2.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-iosX64Main-2.12.0.klib",
          "url": "resource-iosx64-2.12.0.klib",
          "size": 13744,
          "sha512": "919d278ad24c5df8260db1e7659e1f59e82b73c601d3c4bbed7543a3315a0beb17fb9a4e26ba94af6fac7128ee505d91e9864c008b701f7f7c2cf9fde812bbb6",
          "sha256": "a78219bbee9e2d2c5819e0c5ca54d88174d80b4c841e8f71246ea2da64e34c8e",
          "sha1": "95d1fef6f1bb5d29fc7b09e6e8064ef7b7d4ef40",
          "md5": "dd93cf8fac85e4d4e0893a6ed5628285"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-iosx64-2.12.0-metadata.jar",
          "url": "resource-iosx64-2.12.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
