{
  "formatVersion": "1.1",
  "component": {
    "group": "com.riseworld.launchpad.resource",
    "module": "resource",
    "version": "2.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-metadata-2.12.0.jar",
          "url": "resource-2.12.0.jar",
          "size": 3695,
          "sha512": "7e19d5c2270ca651ee440d5d4b0c72bf814eb9dac9f6276107780fb25d035dc0486604048f3ffcdb7bb4bc4471fee06278a6e4df7c848b4d08143d32d3564c67",
          "sha256": "ea75847be13825b3d9ce0c66a84dfb4b3fa9a315ffe795226fe4cafc9e3e10cf",
          "sha1": "896502f8b23f5eeb7a8f6a53ad276574ebed2346",
          "md5": "1988ce95c44808201f482992c5beb525"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-android/2.12.0/resource-android-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-android",
        "version": "2.12.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resource-android/2.12.0/resource-android-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-android",
        "version": "2.12.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-iosarm64/2.12.0/resource-iosarm64-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-iosarm64",
        "version": "2.12.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-iosarm64/2.12.0/resource-iosarm64-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-iosarm64",
        "version": "2.12.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-iossimulatorarm64/2.12.0/resource-iossimulatorarm64-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-iossimulatorarm64",
        "version": "2.12.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-iossimulatorarm64/2.12.0/resource-iossimulatorarm64-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-iossimulatorarm64",
        "version": "2.12.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-iosx64/2.12.0/resource-iosx64-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-iosx64",
        "version": "2.12.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resource-iosx64/2.12.0/resource-iosx64-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-iosx64",
        "version": "2.12.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-jvm/2.12.0/resource-jvm-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-jvm",
        "version": "2.12.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resource-jvm/2.12.0/resource-jvm-2.12.0.module",
        "group": "com.riseworld.launchpad.resource",
        "module": "resource-jvm",
        "version": "2.12.0"
      }
    }
  ]
}
