{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-utils/0.25.6/dynamics-utils-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-utils",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-utils-iosX64Main-0.25.6.klib",
          "url": "dynamics-utils-iosx64-0.25.6.klib",
          "size": 66225,
          "sha512": "7438dae85cb20f79b6f0f5d266f0604b121bcdf6ae9155ebe8056fb11e07a5df741520bd3c7390b90176eb44249e4717a62524d8deedb17a65944ea4200aa701",
          "sha256": "717e02890a76d0a1ad5d35d4a3baf651e6b73c9446ecece915319129952b448f",
          "sha1": "89bdf56e9fe64969ab4371595443a106d2bf8adf",
          "md5": "09c91540eb046fce10e6c54b66df8c5c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.riseworld.launchpad.resource",
          "module": "resource",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-utils-iosx64-0.25.6-metadata.jar",
          "url": "dynamics-utils-iosx64-0.25.6-metadata.jar",
          "size": 3253,
          "sha512": "3aff25990a6782f53660eec28c741eeb4495669c048c2f5e95b8d9569da23cbbc71ab071cd48f26bbb54caf441178993d99cce2200c172cb50ee5e099cf7133a",
          "sha256": "f3f2056bbf029833d0a42356ba93bf49a0488ea0c16c2ee12a4493ca0cda8e15",
          "sha1": "c4625cacca407a2e7d7b0dc7020008588e3aba39",
          "md5": "2e8bf98e6e1289d8c401f27bbf95b34d"
        }
      ]
    }
  ]
}
