{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dynamics-models/0.25.6/dynamics-models-0.25.6.module",
    "group": "com.riseworld.dynamics.multiplatform",
    "module": "dynamics-models",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-iosSimulatorArm64Main-0.25.6.klib",
          "url": "dynamics-models-iossimulatorarm64-0.25.6.klib",
          "size": 333824,
          "sha512": "6d18486abd1b7a507ed6a2d24805a089a506c228f3e7fee415c1ba1a2b18a526af2fe944ecf504f73815c4d926e82638255361f5c0db235580abdeb982ebbd34",
          "sha256": "984eeb19bdd6fc1dab64fd16e290654cf60ec5704bcd8c46930f2a86144502ed",
          "sha1": "f37b63ebbb94baff5e8513c43f5c9969803158fb",
          "md5": "2814ded3acb6c77e7123f8e9441cd2f9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "com.riseworld.dynamics.multiplatform",
          "module": "dynamics-constants",
          "version": {
            "requires": "0.25.6"
          }
        }
      ],
      "files": [
        {
          "name": "dynamics-models-iossimulatorarm64-0.25.6-metadata.jar",
          "url": "dynamics-models-iossimulatorarm64-0.25.6-metadata.jar",
          "size": 9288,
          "sha512": "3e546bbfeb0691c4ec863a99e3896789a8f0cf7e1ac3ef37094240fb9d5b77c46b8a24f923503c92311fd929b223c4c5bfe2008efe89cad4e6bb0a985dde6e4d",
          "sha256": "9214dfa86ed3d2bd21b46866a7ff3267dce7e4fe441bae73a9ed58ea75985fa2",
          "sha1": "54ccaa348e0c092cdcf45cce87cadf3580b77e7d",
          "md5": "a70be39a68b521e4f40790acbacc1dc5"
        }
      ]
    }
  ]
}
